dog_rates_response = [{
  'contributors_enabled': False,
  'created_at': 'Sun Nov 15 21:41:29 +0000 2015',
  'default_profile': False,
  'default_profile_image': False,
  'description': 'Only Legit Source for Professional Dog Ratings STORE: @ShopWeRateDogs | IG, FB & SC: WeRateDogs | MOBILE APP: @GoodDogsGame Business: dogratingtwitter@gmail.com',
  'entities': {
    'description': {'urls': []},
    'url': {
      'urls': [{
        'display_url': 'weratedogs.com',
        'expanded_url': 'http://weratedogs.com',
        'indices': [0, 23],
        'url': 'https://t.co/N7sNNHAEXS'
        }]
      }
  },
  'favourites_count': 122965,
  'follow_request_sent': False,
  'followers_count': 4302332,
  'following': True,
  'friends_count': 109,
  'geo_enabled': True,
  'has_extended_profile': True,
  'id': 4196983835,
  'id_str': '4196983835',
  'is_translation_enabled': False,
  'is_translator': False,
  'lang': 'en',
  'listed_count': 3376,
  'location': 'MERCH↴  DM DOGS. WE WILL RATE',
  'name': 'WeRateDogs™',
  'notifications': False,
  'profile_background_color': '000000',
  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
  'profile_background_tile': False,
  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/4196983835/1510812288',
  'profile_image_url': 'http://pbs.twimg.com/profile_images/925699786963009536/3BtSBv2X_normal.jpg',
  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/925699786963009536/3BtSBv2X_normal.jpg',
  'profile_link_color': 'F5ABB5',
  'profile_sidebar_border_color': '000000',
  'profile_sidebar_fill_color': '000000',
  'profile_text_color': '000000',
  'profile_use_background_image': False,
  'protected': False,
  'screen_name': 'dog_rates',
  'status': {
    'contributors': None,
    'coordinates': None,
    'created_at': 'Mon Nov 20 16:39:57 +0000 2017',
    'entities': {'hashtags': [],
    'symbols': [],
    'urls': [{
      'display_url': 'twitter.com/dog_rates/stat…',
      'expanded_url': 'https://twitter.com/dog_rates/status/932646765253230592',
      'indices': [42, 65],
      'url': 'https://t.co/8LwQq2lppR'
    }],
    'user_mentions': [{
      'id': 588641678,
      'id_str': '588641678',
      'indices': [3, 16],
      'name': 'Elizabeth',
      'screen_name': 'the7thleland'
      }]
    },
    'favorite_count': 0,
    'favorited': False,
    'geo': None,
    'id': 932649727044345857,
    'id_str': '932649727044345857',
    'in_reply_to_screen_name': None,
    'in_reply_to_status_id': None,
    'in_reply_to_status_id_str': None,
    'in_reply_to_user_id': None,
    'in_reply_to_user_id_str': None,
    'is_quote_status': True,
    'lang': 'en',
    'place': None,
    'possibly_sensitive': False,
    'quoted_status_id': 932646765253230592,
    'quoted_status_id_str': '932646765253230592',
    'retweet_count': 14,
    'retweeted': False,
    'retweeted_status': {'contributors': None,
    'coordinates': None,
    'created_at': 'Mon Nov 20 16:37:57 +0000 2017',
    'entities': {
      'hashtags': [],
      'symbols': [],
      'urls': [{
        'display_url': 'twitter.com/dog_rates/stat…',
        'expanded_url': 'https://twitter.com/dog_rates/status/932646765253230592',
        'indices': [24, 47],
        'url': 'https://t.co/8LwQq2lppR'
      }],
     'user_mentions': []
     },
     'favorite_count': 136,
     'favorited': False,
     'geo': None,
     'id': 932649226160492545,
     'id_str': '932649226160492545',
     'in_reply_to_screen_name': None,
     'in_reply_to_status_id': None,
     'in_reply_to_status_id_str': None,
     'in_reply_to_user_id': None,
     'in_reply_to_user_id_str': None,
     'is_quote_status': True,
     'lang': 'en',
     'place': None,
     'possibly_sensitive': False,
     'quoted_status_id': 932646765253230592,
     'quoted_status_id_str': '932646765253230592',
     'retweet_count': 14,
     'retweeted': False,
     'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
     'text': 'H*ck the Halls.....yes. https://t.co/8LwQq2lppR',
     'truncated': False},
     'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
     'text': 'RT @the7thleland: H*ck the Halls.....yes. https://t.co/8LwQq2lppR',
     'truncated': False
    },
   'statuses_count': 6065,
   'time_zone': None,
   'translator_type': 'none',
   'url': 'https://t.co/N7sNNHAEXS',
   'utc_offset': None,
   'verified': True
}]
